### ISSUE TITLE
*.xsemantics files are processed even if they are not in a source folder

### ISSUE THREAD

**Issue by lwrage** [eclipse/xsemantics#81]
I use xsemantics in a plugin that is built with tycho. Tycho creates class files under target/classes and xsemantics files are copied to target/classes. Each copied xsemantics file `xyz.xsemantics` gets an error marker for the `system XYZ` declaration line: "The type XYZ is already defined in xyz.xsemantics." It seems that some validation is run on the copied xsemantics files which detects a naming conflict. Can the processing of xsemantics files be restricted to source folders in the project, or is there a way to at least exclude the target folder?
I need the copied files because I extend the system in another plugin.

**Comment by LorenzoBettini** [comment]
Hi
I guess you're using xtext-maven-plugin to process Xsemantics files during the build, right?
Could it be due to the way you configured that plugin?
By the way, which version of Xsemantics/Xtext are you using?

**Comment by lwrage** [comment]
Eclipse Mars.2, Xtext 2.8.4, Xsemantics 1.8.1
The issue is independent of the tycho build: Take a project that contains an xsemantics file in a source folder. Create a new folder in the project (don't make it a source folder). Copy the xsemantics file to the new folder. The copied file get an error marker attached, so it's processed even though it is not in a source folder. I have auto-build on, otherwise it happens during a manual build.

**Comment by LorenzoBettini** [comment]
I seem to remember that this is due to a bug in Xtext that has been fixed in the latest versions, that's why I asked; I'll check whether I can reproduce the problem with the current version of Xsemantics/Xtext, but I think it's related to the old version of Xtext that you're using...

**Comment by lwrage** [comment]
I see the same behavior after upgrading to Xtext 2.11.0 and Xsemantics 1.11.0 (still on Mars.2)

**Comment by LorenzoBettini** [comment]
I can't check it now, but have you had a look at this discussion? https://www.eclipse.org/forums/index.php/t/1075958/

**Comment by lwrage** [comment]
I looked at the discussion, but I don't see anything that I could change in my project to avoid the issue. 
By the way, the situation is still the same with eclipse 2018-09, Xtext 2.15.0, and Xsemantics 2.15.0.

**Comment by lwrage** [comment]
Is this what you're asking for?

![image](https://user-images.githubusercontent.com/750311/50012903-d7c0ab80-ff8d-11e8-85ad-869aa4c03a5e.png)

**Comment by cdietrich** [comment]
No I mean regarding maven

**Comment by lwrage** [comment]
The issue occurs independent of a tycho/maven build. See my comment above: https://github.com/eclipse/xsemantics/issues/81#issuecomment-273280052

**Comment by cdietrich** [comment]
So why do you then copy the file to the second folder in the first place

**Comment by lwrage** [comment]
I did it to simulate what happened during the maven build to show that it is not a maven issue.

OK, the tycho/maven build has changed! The xsemantics files are no longer copied to target/classes/... but they are still included in the jar file. So everything is fine.

But a question: It seems that there is no way to configure Xtext to ignore files that are not in a source folder. Wouldn't it make sense to have such an option?
